# Additional git repositories to pull
git_repos = [
   "~/projects/*/",
   "~/.oh-my-zsh/plugins/zsh-autosuggestions"
   "~/.oh-my-zsh/plugins/zsh-completions"
   "~/.oh-my-zsh/plugins/zsh-syntax-highlighting"
]

# Don't pull the predefined git repos
# predefined_git_repos = false

# Do not ask to retry failed steps (default: false)
#no_retry = true

# Arguments to pass Git when pulling Repositories
#git_arguments = "--rebase --autostash"

# Arguments to pass yay when updating packages
#yay_arguments = "--nodevel"

# Commands to run before anything
[pre_commands]
"RPull" = "rpull -a"
#"Emacs Snapshot" = "rm -rf ~/.emacs.d/elpa.bak && cp -rl ~/.emacs.d/elpa ~/.emacs.d/elpa.bak"

# Custom commands
[commands]
"Update pass store" = "pass git pull"
"Link new dot files" = "~/dotfiles_and_friends/.linkfiles"

# Cleanup temporary or old files
#cleanup = true
